blank_issues_enabled: false
contact_links:
  - name: Existing issues
    url: https://github.com/AustralianCancerDataNetwork/hemonc-alchemy/issues
    about: Search existing issues before opening a new report.
